# Generated by Django 5.2.1 on 2025-05-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atienda', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
